version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    container_name: dotfiles-test

    # Keep container running
    stdin_open: true
    tty: true

    # Environment variables
    environment:
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8

    # Working directory
    working_dir: /home/testuser

    # Optional: Mount local dotfiles for development
    # Uncomment to test local changes without pushing to GitHub
    # volumes:
    #   - ~/.local/share/dotfiles:/home/testuser/.local/share/dotfiles:ro

    # Optional: Persist data between container restarts
    # volumes:
    #   - dotfiles-home:/home/testuser

    # User
    user: testuser

    # Command to run
    command: /bin/bash

# Optional: Define volumes for persistence
# volumes:
#   dotfiles-home:
